name: CI/CD Пайплайн

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Запуск тестов
    runs-on: ubuntu-latest
    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Настроить Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'

      - name: Получить зависимости
        run: go mod tidy

      - name: Запустить линтеры
        run: go vet ./...

      - name: Запустить тесты
        run: go test -v ./...

  publish:
    name: Опубликовать Docker-образ
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Настроить Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Войти в DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Извлечь метаданные (теги, метки) для Docker-образа
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            haywnink/myapp

      - name: Собрать и отправить Docker-образ
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}